// utils/tools/emailChecker.ts

export async function checkEmail(email: string) {
  let score = 100;
  const messages: string[] = [];

  // ===================== 1. FORMAT =====================
  const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!regex.test(email)) {
    return {
      score: 0,
      status: "danger",
      messages: ["Invalid email format"],
    };
  }

  const [localPart, domain] = email.split("@");

  // ===================== 2. LOCAL PART CHECK =====================
  // Détecte les patterns suspects dans le local part
  if (/^[0-9]+$/.test(localPart)) {
    score -= 10;
    messages.push("Email local part is numeric");
  }

  if (/^[a-z]{1,2}[0-9]{2,}/i.test(localPart)) {
    score -= 5;
    messages.push("Email local part looks autogenerated");
  }

  // ===================== 3. DOMAIN CHECK =====================
  const disposableDomains = [
    "tempmail.com",
    "10minutemail.com",
    "guerrillamail.com",
    "mailinator.com",
    "yopmail.com",
  ];

  if (disposableDomains.includes(domain.toLowerCase())) {
    score -= 40;
    messages.push("Disposable email detected");
  }

  // Détection de mots clés suspects dans le domaine
  if (/secure|verify|account|update|login/i.test(domain)) {
    score -= 20;
    messages.push("Suspicious domain keywords");
  }

  // Détection de domaine très long ou bizarre
  if (domain.length > 30) {
    score -= 10;
    messages.push("Domain name unusually long");
  }

  // Entropy (caractères random) pour suspicion
  const entropy = new Set(domain).size / domain.length;
  if (entropy > 0.8) {
    score -= 10;
    messages.push("High entropy domain (looks suspicious)");
  }

  // ===================== 4. MX RECORD CHECK (simulé) =====================
  // Local et rapide : on simule vérif DNS
  const mxSuspicious = ["spamdomain.com", "fake-mail.net"];
  if (mxSuspicious.includes(domain.toLowerCase())) {
    score -= 30;
    messages.push("Domain MX records flagged (local DB)");
  }

  // ===================== 5. FINAL SCORING =====================
  let status = "safe";
  if (score < 50) status = "danger";
  else if (score < 80) status = "warning";

  return { score, status, messages };
}
