// utils/tools/emailChecker.ts

export async function checkEmail(email: string) {
  let score = 100;
  const messages: string[] = [];

  // ===================== 1. FORMAT =====================
  const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!regex.test(email)) {
    return {
      score: 0,
      status: "danger",
      messages: ["toolsUtils.emailChecker.messages.invalidFormat"],
    };
  }

  const [localPart, domain] = email.split("@");

  // ===================== 2. LOCAL PART CHECK =====================
  if (/^[0-9]+$/.test(localPart)) {
    score -= 10;
    messages.push("toolsUtils.emailChecker.messages.numericLocalPart");
  }

  if (/^[a-z]{1,2}[0-9]{2,}/i.test(localPart)) {
    score -= 5;
    messages.push("toolsUtils.emailChecker.messages.autogeneratedLocalPart");
  }

  // ===================== 3. DOMAIN CHECK =====================
  const disposableDomains = [
    "tempmail.com",
    "10minutemail.com",
    "guerrillamail.com",
    "mailinator.com",
    "yopmail.com",
  ];

  if (disposableDomains.includes(domain.toLowerCase())) {
    score -= 40;
    messages.push("toolsUtils.emailChecker.messages.disposableEmail");
  }

  if (/secure|verify|account|update|login/i.test(domain)) {
    score -= 20;
    messages.push("toolsUtils.emailChecker.messages.suspiciousDomainKeywords");
  }

  if (domain.length > 30) {
    score -= 10;
    messages.push("toolsUtils.emailChecker.messages.longDomain");
  }

  const entropy = new Set(domain).size / domain.length;
  if (entropy > 0.8) {
    score -= 10;
    messages.push("toolsUtils.emailChecker.messages.highEntropyDomain");
  }

  // ===================== 4. MX RECORD CHECK (simulé) =====================
  const mxSuspicious = ["spamdomain.com", "fake-mail.net"];
  if (mxSuspicious.includes(domain.toLowerCase())) {
    score -= 30;
    messages.push("toolsUtils.emailChecker.messages.flaggedMx");
  }

  // ===================== 5. FINAL SCORING =====================
  let status = "safe";
  if (score < 50) status = "danger";
  else if (score < 80) status = "warning";

  return { score, status, messages };
}
